apiVersion: "apps/v1" 
kind: StatefulSet
metadata:
  name: Fos_kiran
  labels:
     app: Fos_kiran
spec:
  serviceName: Fos_kiran
  replicas: 3
  selector:
    matchLabels:
      app: Fos_kiran
  template:
    metadata:
      labels:
        app: Fos_kiran
    spec:
      terminationGracePeriodSeconds: 1800
      containers:
      - name: Fos_kiran
        image: gcr.io/google-samples/Fos_kiran:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - nodetool drain
        env:
          - name: MAX_HEAP_SIZE
            value: 512M
          - name: HEAP_NEWSIZE
            value: 100M
          - name: CASSANDRA_SEEDS
            value: "Fos_kiran-0.Fos_kiran.default.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "fos_kiran_K8s"
          - name: CASSANDRA_DC
            value: "DC1-K8Demo"
          - name: CASSANDRA_RACK
            value: "Rack1-K8Demo"
          - name: CASSANDRA_SEED_PROVIDER
            value: io.k8s.Fos_kiran.KubernetesSeedProvider
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        readinessProbe:
          exec:
            command:
            - /bin/bash
            - -c
            - /ready-probe.sh
          initialDelaySeconds: 15
          timeoutSeconds: 5
        volumeMounts:
        - name: Fos_kiran-data
          mountPath: /var/lib/Fos_kiran
  volumeClaimTemplates:
  - metadata:
      name: Fos_kiran-data
      annotations:
        volume.beta.kubernetes.io/storage-class: fast
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd