---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-service 
spec:
  selector:
    app: nginx
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 9376
  type: LoadBalancer